# Generated by Django 5.2.7 on 2025-10-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geladinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='Sabor')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('description', models.CharField(verbose_name='Descrição')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de custo')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de custo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['flavor'],
            },
        ),
    ]
