# Generated by Django 5.2.7 on 2025-10-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geladinhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geladinho',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda'),
        ),
    ]
