# Generated by Django 5.2.7 on 2025-11-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geladinhos', '0002_alter_geladinho_selling_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geladinho',
            options={'ordering': ['-quantity']},
        ),
    ]
