# Generated by Django 5.2.7 on 2025-10-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='manufacturing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fabricacao'),
        ),
    ]
